### ISSUE TITLE
[Query] Context of negative anomaly scores

### ISSUE THREAD

**Issue by L-Marriott** [yzhao062/SUOD#10]
I'm not report an issue per se, but I'm curious if there's meaning behind a negative anomaly score? 

It seems intuitive to me that scores would vary between 0 and 1

**Comment by yzhao062** [comment]
Hi there. The absolute value of outlier scores are not important. The relevant rank matters though. You could always rescale the scores into the range of 0 and 1, where the order/rank stays the same.

**Comment by L-Marriott** [comment]
Thanks, that makes sense!
